spring:
  application:
    name: mtgo-twitch-extension-backend

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

mtgo:
  log:
    path: ${MTGO_LOG_PATH:}

twitch:
  client-id: ${TWITCH_CLIENT_ID:}
